import { useEffect, useState } from 'react'
import { api } from '../lib/api.js'
import { Loading, ErrorState } from '../components/States.jsx'
import { useToast } from '../components/Toast.jsx'

const TONES = ['professional', 'friendly', 'concise', 'consultative']

export default function Settings() {
  const toast = useToast()
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [values, setValues] = useState(null)
  const [saving, setSaving] = useState(false)

  const load = () => {
    setError(null)
    api.get('/settings').then((d) => { setData(d); setValues(d.values) }).catch((e) => setError(e.message))
  }
  useEffect(load, [])

  if (error) return <ErrorState message={error} onRetry={load} />
  if (!data || !values) return <Loading />

  const set = (k, v) => setValues((s) => ({ ...s, [k]: v }))

  const save = async () => {
    setSaving(true)
    try {
      await api.put('/settings', {
        company_name: values.company_name,
        rep_name: values.rep_name,
        rep_email: values.rep_email,
        notify_on_hot_lead: !!values.notify_on_hot_lead,
        default_email_tone: values.default_email_tone,
        follow_up_days: Number(values.follow_up_days) || 5,
      })
      toast.success('Settings saved')
      load()
    } catch (e) { toast.error(e.message) } finally { setSaving(false) }
  }

  return (
    <div className="space-y-4 max-w-3xl">
      <div>
        <h1 className="text-2xl font-bold">Settings</h1>
        <p className="text-sm text-slate-500">Workspace configuration</p>
      </div>

      <div className="card p-5 space-y-4">
        <h2 className="font-semibold">Company profile</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="label">Company name</label>
            <input className="input" value={values.company_name || ''} onChange={(e) => set('company_name', e.target.value)} />
          </div>
          <div>
            <label className="label">Sales rep name</label>
            <input className="input" value={values.rep_name || ''} onChange={(e) => set('rep_name', e.target.value)} />
          </div>
          <div>
            <label className="label">Rep email</label>
            <input className="input" value={values.rep_email || ''} onChange={(e) => set('rep_email', e.target.value)} />
          </div>
          <div>
            <label className="label">Follow-up delay (days)</label>
            <input type="number" min="1" className="input" value={values.follow_up_days ?? 5}
              onChange={(e) => set('follow_up_days', e.target.value)} />
          </div>
          <div>
            <label className="label">Default email tone</label>
            <select className="input" value={values.default_email_tone || 'professional'}
              onChange={(e) => set('default_email_tone', e.target.value)}>
              {TONES.map((t) => <option key={t} value={t}>{t}</option>)}
            </select>
          </div>
          <label className="flex items-center gap-2 mt-6 text-sm">
            <input type="checkbox" checked={!!values.notify_on_hot_lead}
              onChange={(e) => set('notify_on_hot_lead', e.target.checked)} />
            Notify me when a lead turns hot
          </label>
        </div>
        <div className="flex justify-end">
          <button className="btn-primary" onClick={save} disabled={saving}>{saving ? 'Saving…' : 'Save settings'}</button>
        </div>
      </div>

      <div className="card p-5">
        <h2 className="font-semibold mb-3">AI provider</h2>
        <div className="flex items-center gap-3 text-sm">
          <span className={`badge ${data.ai_provider === 'openai' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>
            {data.ai_provider === 'openai' ? 'OpenAI-compatible API connected' : 'Demo mode (built-in personalization engine)'}
          </span>
          <span className="text-slate-500 text-xs">
            {data.ai_provider === 'openai'
              ? 'Emails are generated via the connected LLM gateway.'
              : 'Emails are generated by the built-in deterministic personalization engine — the full workflow works without any external service.'}
          </span>
        </div>
      </div>

      <div className="card p-5">
        <h2 className="font-semibold mb-1">Scoring model</h2>
        <p className="text-xs text-slate-500 mb-3">
          Backend: <strong>{data.model_backend}</strong> — transparent weighted engine, ML-ready interface.
        </p>
        <div className="space-y-2">
          {Object.entries(data.scoring_weights).map(([k, w]) => (
            <div key={k} className="flex items-center gap-3 text-xs">
              <span className="w-36 text-slate-600">{k.replace('_', ' ')}</span>
              <div className="flex-1 h-2 bg-slate-100 rounded-full">
                <div className="h-full bg-brand-500 rounded-full" style={{ width: `${w * 3.3}%` }} />
              </div>
              <span className="w-8 text-right text-slate-500">{w}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
